title: Hashino's Page
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Pagination settings
plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

# License
license: MIT
